### ISSUE TITLE
don't know why my fork does't work

### ISSUE THREAD

**Issue by HagridThick** [YouEclipse/steam-box#1]
I create a gist , then add it in workflow's file.
and add 3 secret tokens

**Comment by YouEclipse** [comment]
Does the workflow works?

**Comment by YouEclipse** [comment]
or you can post your repo address，I'll see what's wrong.

**Comment by HagridThick** [comment]
i dont know how to see whether workflow works or not.

this is my forked repo
https://github.com/HagridThick/steam-box

**Comment by YouEclipse** [comment]
> i dont know how to see whether workflow works or not.
> 
> this is my forked repo
> https://github.com/HagridThick/steam-box

Try to delete the schedule.yml then add a new one. it should be a bug of github actions.
