### ISSUE TITLE
If the game name contains Chinese, there is a problem with formatting.

### ISSUE THREAD

**Issue by homurax** [YouEclipse/steam-box#3]
https://github.com/YouEclipse/steam-box/blob/77b2872e59a6b4aa9444d6ccf1b8e247a058c430/pkg/steambox/box.go#L84

The generated content is not aligned.
like this:
https://gist.github.com/homurax/c2ca1c7de88d5f83b033aa02fa4a82a1

Should targetLength be obtained by calculation instead of specified？

**Comment by YouEclipse** [comment]
thanks for the feedback. will fix it later.

**Comment by YouEclipse** [comment]
https://github.com/YouEclipse/steam-box/commit/0d44a208f4dfa243d91fc7b2606d35e067d42229
